language: python
python:
    - 2.7
    - 3.4
    - pypy

before_install:
    - sudo apt-get purge elasticsearch -fy
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.1.deb
    - sudo dpkg -i elasticsearch-1.2.1.deb
    - sudo service elasticsearch restart
    - sleep 10  # Let it breathe! :D

install:
    - make setup
    - python setup.py install

before_script:
    - curl http://localhost:9200/  # Check if ES is up and listening
    - ./run bulk

script:
    - make test
